import Foundation

// 言語定義
enum AppLanguage: String, CaseIterable, Identifiable, Codable {
    case system = "System Default" // 内部IDとして使用、表示名は辞書で変換
    case japanese = "日本語"
    case english = "English"
    case german = "Deutsch"
    case french = "Français"
    case spanish = "Español"
    case korean = "한국어"
    case chineseSimplified = "简体中文"
    case chineseTraditional = "繁體中文"
    case portugueseBrazil = "Português (Brasil)"
    case russian = "Русский"
    
    var id: String { self.rawValue }
}

class LocalizationManager {
    static let shared = LocalizationManager()
    
    // 現在有効な言語を判定
    func resolveLanguage(_ language: AppLanguage) -> AppLanguage {
        if language == .system {
            let preferredLang = Locale.preferredLanguages.first ?? "en"
            
            if preferredLang.hasPrefix("ja") { return .japanese }
            if preferredLang.hasPrefix("de") { return .german }
            if preferredLang.hasPrefix("fr") { return .french }
            if preferredLang.hasPrefix("es") { return .spanish }
            if preferredLang.hasPrefix("ko") { return .korean }
            
            if preferredLang.hasPrefix("zh") {
                if preferredLang.contains("Hant") || preferredLang.contains("TW") || preferredLang.contains("HK") {
                    return .chineseTraditional
                }
                return .chineseSimplified
            }
            
            if preferredLang.hasPrefix("pt") { return .portugueseBrazil }
            if preferredLang.hasPrefix("ru") { return .russian }
            
            return .english
        }
        return language
    }
    
    // 翻訳辞書
    private let translations: [AppLanguage: [String: String]] = [
        .japanese: [
            "systemDefault": "システムに合わせる",
            "windowTitle": "Windoor 設定",
            "languageSettings": "言語設定",
            "conflictWarning": "設定が重複しています",
            "moveWindow": "ウィンドウの移動",
            "resizeWindow": "ウィンドウのリサイズ",
            "anchorPoint": "アンカーポイント",
            "topLeft": "左上",
            "topRight": "右上",
            "bottomLeft": "左下",
            "bottomRight": "右下",
            "nearestCorner": "近い角",
            "farthestCorner": "遠い角",
            "modifierKey": "修飾キー",
            "click": "クリック",
            "leftClickOnlyWarning": "左クリックのみに設定することはできません",
            "modifierOnly": "修飾キーのみ",
            "axisConstraint": "方向を制限",
            "axisConstraintDesc": "ドラッグ中に指定キーを押すと、開始位置から一方向だけに操作します。",
            "horizontalOnly": "横方向のみ",
            "verticalOnly": "縦方向のみ",
            "detailSettings": "詳細設定",
            "longPressDuration": "長押し確定の時間",
            "longPressDesc": "「修飾キーのみ」がオンの場合、キーを押し続けると確定します。",
            "preserveWindowOrder": "ウィンドウの配置を維持",
            "showMenuBarIcon": "メニューバーアイコンを表示",
            "launchAtLogin": "ログイン時に自動実行",
            "restart": "再起動",
            "quit": "終了",
            "quitAlertTitle": "Windoorを終了",
            "quitAlertMessage": "アプリを終了してもよろしいですか？\nウィンドウ操作機能が停止します。",
            "cancel": "キャンセル",
            "inputKey": "キーを入力...",
            "inputLongPress": "長押しで確定...",
            "notSet": "未設定",
            "sec": "秒",
            "leftClick": "左クリック",
            "rightClick": "右クリック",
            "centerClick": "ホイール(中)",
            "menuSettings": "設定...",
            "menuRestart": "Windoorを再起動",
            "menuQuit": "Windoorを終了"
        ],
        .english: [
            "systemDefault": "System Default",
            "windowTitle": "Windoor Settings",
            "languageSettings": "Language",
            "conflictWarning": "Configuration Conflict",
            "moveWindow": "Move Window",
            "resizeWindow": "Resize Window",
            "anchorPoint": "Anchor Point",
            "topLeft": "Top Left",
            "topRight": "Top Right",
            "bottomLeft": "Bottom Left",
            "bottomRight": "Bottom Right",
            "nearestCorner": "Nearest Corner",
            "farthestCorner": "Farthest Corner",
            "modifierKey": "Modifier Key",
            "click": "Click",
            "leftClickOnlyWarning": "Left click alone cannot be configured",
            "modifierOnly": "Modifier Only",
            "axisConstraint": "Axis Constraint",
            "axisConstraintDesc": "Hold the assigned key while dragging to constrain from the drag origin.",
            "horizontalOnly": "Horizontal Only",
            "verticalOnly": "Vertical Only",
            "detailSettings": "Advanced Settings",
            "longPressDuration": "Long Press Duration",
            "longPressDesc": "Hold key to confirm when 'Modifier Only' is on.",
            "preserveWindowOrder": "Preserve Window Order",
            "showMenuBarIcon": "Show Menu Bar Icon",
            "launchAtLogin": "Launch at Login",
            "restart": "Restart",
            "quit": "Quit",
            "quitAlertTitle": "Quit Windoor",
            "quitAlertMessage": "Are you sure you want to quit?\nWindow management features will stop.",
            "cancel": "Cancel",
            "inputKey": "Press Key...",
            "inputLongPress": "Hold to Confirm...",
            "notSet": "Not Set",
            "sec": "s",
            "leftClick": "Left Click",
            "rightClick": "Right Click",
            "centerClick": "Middle Click",
            "menuSettings": "Settings...",
            "menuRestart": "Restart Windoor",
            "menuQuit": "Quit Windoor"
        ],
        .german: [
            "systemDefault": "Systemstandard",
            "windowTitle": "Windoor Einstellungen",
            "languageSettings": "Sprache",
            "conflictWarning": "Konflikt bei Einstellungen",
            "moveWindow": "Fenster verschieben",
            "resizeWindow": "Fenstergröße ändern",
            "anchorPoint": "Ankerpunkt",
            "topLeft": "Oben links",
            "topRight": "Oben rechts",
            "bottomLeft": "Unten links",
            "bottomRight": "Unten rechts",
            "nearestCorner": "Nächste Ecke",
            "farthestCorner": "Entfernteste Ecke",
            "modifierKey": "Modifikatortaste",
            "click": "Klick",
            "leftClickOnlyWarning": "Nur Linksklick kann nicht eingestellt werden",
            "modifierOnly": "Nur Modifikator",
            "axisConstraint": "Achsenbegrenzung",
            "axisConstraintDesc": "Zugewiesene Taste beim Ziehen halten, um ab dem Startpunkt eine Achse zu verwenden.",
            "horizontalOnly": "Nur horizontal",
            "verticalOnly": "Nur vertikal",
            "detailSettings": "Erweiterte Einstellungen",
            "longPressDuration": "Dauer für langes Drücken",
            "longPressDesc": "Taste gedrückt halten zum Bestätigen.",
            "preserveWindowOrder": "Fensterreihenfolge beibehalten",
            "showMenuBarIcon": "Menüleistensymbol anzeigen",
            "launchAtLogin": "Beim Anmelden starten",
            "restart": "Neustart",
            "quit": "Beenden",
            "quitAlertTitle": "Windoor beenden",
            "quitAlertMessage": "Möchten Sie wirklich beenden?",
            "cancel": "Abbrechen",
            "inputKey": "Taste drücken...",
            "inputLongPress": "Gedrückt halten...",
            "notSet": "Nicht gesetzt",
            "sec": "s",
            "leftClick": "Linksklick",
            "rightClick": "Rechtsklick",
            "centerClick": "Mittelklick",
            "menuSettings": "Einstellungen...",
            "menuRestart": "Windoor neu starten",
            "menuQuit": "Windoor beenden"
        ],
        .french: [
            "systemDefault": "Système par défaut",
            "windowTitle": "Paramètres Windoor",
            "languageSettings": "Langue",
            "conflictWarning": "Conflit de configuration",
            "moveWindow": "Déplacer la fenêtre",
            "resizeWindow": "Redimensionner",
            "anchorPoint": "Point d’ancrage",
            "topLeft": "En haut à gauche",
            "topRight": "En haut à droite",
            "bottomLeft": "En bas à gauche",
            "bottomRight": "En bas à droite",
            "nearestCorner": "Coin le plus proche",
            "farthestCorner": "Coin le plus éloigné",
            "modifierKey": "Touche modif.",
            "click": "Clic",
            "leftClickOnlyWarning": "Le clic gauche seul ne peut pas être configuré",
            "modifierOnly": "Modif. uniquement",
            "axisConstraint": "Contrainte d’axe",
            "axisConstraintDesc": "Maintenez la touche assignée pendant le glissement pour limiter le mouvement à un axe.",
            "horizontalOnly": "Horizontal seulement",
            "verticalOnly": "Vertical seulement",
            "detailSettings": "Paramètres avancés",
            "longPressDuration": "Durée appui long",
            "longPressDesc": "Maintenez pour confirmer si 'Modif. uniquement' est actif.",
            "preserveWindowOrder": "Préserver l'ordre des fenêtres",
            "showMenuBarIcon": "Afficher l’icône de la barre des menus",
            "launchAtLogin": "Lancer à la connexion",
            "restart": "Redémarrer",
            "quit": "Quitter",
            "quitAlertTitle": "Quitter Windoor",
            "quitAlertMessage": "Voulez-vous vraiment quitter ?",
            "cancel": "Annuler",
            "inputKey": "Appuyez...",
            "inputLongPress": "Maintenez...",
            "notSet": "Non défini",
            "sec": "s",
            "leftClick": "Clic gauche",
            "rightClick": "Clic droit",
            "centerClick": "Clic milieu",
            "menuSettings": "Paramètres...",
            "menuRestart": "Redémarrer Windoor",
            "menuQuit": "Quitter Windoor"
        ],
        .spanish: [
            "systemDefault": "Predeterminado del sistema",
            "windowTitle": "Configuración Windoor",
            "languageSettings": "Idioma",
            "conflictWarning": "Conflicto de configuración",
            "moveWindow": "Mover ventana",
            "resizeWindow": "Redimensionar",
            "anchorPoint": "Punto de anclaje",
            "topLeft": "Superior izquierda",
            "topRight": "Superior derecha",
            "bottomLeft": "Inferior izquierda",
            "bottomRight": "Inferior derecha",
            "nearestCorner": "Esquina más cercana",
            "farthestCorner": "Esquina más lejana",
            "modifierKey": "Tecla modificadora",
            "click": "Clic",
            "leftClickOnlyWarning": "No se puede configurar solo el clic izquierdo",
            "modifierOnly": "Solo modificador",
            "axisConstraint": "Restricción de eje",
            "axisConstraintDesc": "Mantenga la tecla asignada al arrastrar para limitar la operación a un eje.",
            "horizontalOnly": "Solo horizontal",
            "verticalOnly": "Solo vertical",
            "detailSettings": "Ajustes avanzados",
            "longPressDuration": "Duración pulsación larga",
            "longPressDesc": "Mantenga pulsado para confirmar.",
            "preserveWindowOrder": "Mantener el orden de las ventanas",
            "showMenuBarIcon": "Mostrar icono en la barra de menús",
            "launchAtLogin": "Ejecutar al iniciar sesión",
            "restart": "Reiniciar",
            "quit": "Salir",
            "quitAlertTitle": "Salir de Windoor",
            "quitAlertMessage": "¿Seguro que quieres salir?",
            "cancel": "Cancelar",
            "inputKey": "Presione tecla...",
            "inputLongPress": "Mantenga...",
            "notSet": "No establecido",
            "sec": "s",
            "leftClick": "Clic izquierdo",
            "rightClick": "Clic derecho",
            "centerClick": "Clic central",
            "menuSettings": "Ajustes...",
            "menuRestart": "Reiniciar Windoor",
            "menuQuit": "Salir de Windoor"
        ],
        .korean: [
            "systemDefault": "시스템 기본값",
            "windowTitle": "Windoor 설정",
            "languageSettings": "언어",
            "conflictWarning": "설정 충돌",
            "moveWindow": "창 이동",
            "resizeWindow": "창 크기 조절",
            "anchorPoint": "앵커 포인트",
            "topLeft": "왼쪽 위",
            "topRight": "오른쪽 위",
            "bottomLeft": "왼쪽 아래",
            "bottomRight": "오른쪽 아래",
            "nearestCorner": "가까운 모서리",
            "farthestCorner": "먼 모서리",
            "modifierKey": "수식 키",
            "click": "클릭",
            "leftClickOnlyWarning": "왼쪽 클릭만으로 설정할 수 없습니다",
            "modifierOnly": "수식 키만 사용",
            "axisConstraint": "축 제한",
            "axisConstraintDesc": "드래그 중 지정 키를 누르면 시작 위치를 기준으로 한 축으로 제한합니다.",
            "horizontalOnly": "가로 방향만",
            "verticalOnly": "세로 방향만",
            "detailSettings": "고급 설정",
            "longPressDuration": "길게 누르기 시간",
            "longPressDesc": "'수식 키만 사용'이 켜져 있으면 길게 눌러 확정합니다.",
            "preserveWindowOrder": "창 순서 유지",
            "showMenuBarIcon": "메뉴 막대 아이콘 표시",
            "launchAtLogin": "로그인 시 자동 실행",
            "restart": "재시작",
            "quit": "종료",
            "quitAlertTitle": "Windoor 종료",
            "quitAlertMessage": "정말 종료하시겠습니까?",
            "cancel": "취소",
            "inputKey": "키 입력...",
            "inputLongPress": "길게 눌러 확정...",
            "notSet": "미설정",
            "sec": "초",
            "leftClick": "좌클릭",
            "rightClick": "우클릭",
            "centerClick": "휠 클릭",
            "menuSettings": "설정...",
            "menuRestart": "Windoor 재시작",
            "menuQuit": "Windoor 종료"
        ],
        .chineseSimplified: [
            "systemDefault": "跟随系统",
            "windowTitle": "Windoor 设置",
            "languageSettings": "语言",
            "conflictWarning": "配置冲突",
            "moveWindow": "移动窗口",
            "resizeWindow": "调整大小",
            "anchorPoint": "锚点",
            "topLeft": "左上",
            "topRight": "右上",
            "bottomLeft": "左下",
            "bottomRight": "右下",
            "nearestCorner": "最近的角",
            "farthestCorner": "最远的角",
            "modifierKey": "修饰键",
            "click": "点击",
            "leftClickOnlyWarning": "不能只设置左键点击",
            "modifierOnly": "仅修饰键",
            "axisConstraint": "轴向限制",
            "axisConstraintDesc": "拖动时按住指定按键，将操作限制为从起点开始的单一方向。",
            "horizontalOnly": "仅横向",
            "verticalOnly": "仅纵向",
            "detailSettings": "高级设置",
            "longPressDuration": "长按确认时间",
            "longPressDesc": "开启“仅修饰键”时，长按以确认。",
            "preserveWindowOrder": "保持窗口顺序",
            "showMenuBarIcon": "显示菜单栏图标",
            "launchAtLogin": "登录时自动启动",
            "restart": "重新启动",
            "quit": "退出",
            "quitAlertTitle": "退出 Windoor",
            "quitAlertMessage": "确定要退出吗？",
            "cancel": "取消",
            "inputKey": "输入按键...",
            "inputLongPress": "长按确认...",
            "notSet": "未设置",
            "sec": "秒",
            "leftClick": "左键",
            "rightClick": "右键",
            "centerClick": "中键",
            "menuSettings": "设置...",
            "menuRestart": "重新启动 Windoor",
            "menuQuit": "退出 Windoor"
        ],
        .chineseTraditional: [
            "systemDefault": "系統預設",
            "windowTitle": "Windoor 設定",
            "languageSettings": "語言",
            "conflictWarning": "設定衝突",
            "moveWindow": "移動視窗",
            "resizeWindow": "調整大小",
            "anchorPoint": "錨點",
            "topLeft": "左上",
            "topRight": "右上",
            "bottomLeft": "左下",
            "bottomRight": "右下",
            "nearestCorner": "最近的角",
            "farthestCorner": "最遠的角",
            "modifierKey": "修飾鍵",
            "click": "點擊",
            "leftClickOnlyWarning": "不能只設定左鍵點擊",
            "modifierOnly": "僅修飾鍵",
            "axisConstraint": "軸向限制",
            "axisConstraintDesc": "拖曳時按住指定按鍵，將操作限制為從起點開始的單一方向。",
            "horizontalOnly": "僅橫向",
            "verticalOnly": "僅縱向",
            "detailSettings": "進階設定",
            "longPressDuration": "長按確認時間",
            "longPressDesc": "開啟「僅修飾鍵」時，長按以確認。",
            "preserveWindowOrder": "保持視窗順序",
            "showMenuBarIcon": "顯示選單列圖示",
            "launchAtLogin": "登入時自動啟動",
            "restart": "重新啟動",
            "quit": "結束",
            "quitAlertTitle": "結束 Windoor",
            "quitAlertMessage": "確定要結束嗎？",
            "cancel": "取消",
            "inputKey": "輸入按鍵...",
            "inputLongPress": "長按確認...",
            "notSet": "未設定",
            "sec": "秒",
            "leftClick": "左鍵",
            "rightClick": "右鍵",
            "centerClick": "中鍵",
            "menuSettings": "設定...",
            "menuRestart": "重新啟動 Windoor",
            "menuQuit": "結束 Windoor"
        ],
        .portugueseBrazil: [
            "systemDefault": "Padrão do Sistema",
            "windowTitle": "Configurações Windoor",
            "languageSettings": "Idioma",
            "conflictWarning": "Conflito de configuração",
            "moveWindow": "Mover Janela",
            "resizeWindow": "Redimensionar",
            "anchorPoint": "Ponto de ancoragem",
            "topLeft": "Superior esquerdo",
            "topRight": "Superior direito",
            "bottomLeft": "Inferior esquerdo",
            "bottomRight": "Inferior direito",
            "nearestCorner": "Canto mais próximo",
            "farthestCorner": "Canto mais distante",
            "modifierKey": "Tecla Modificadora",
            "click": "Clique",
            "leftClickOnlyWarning": "Não é possível configurar apenas o clique esquerdo",
            "modifierOnly": "Apenas Modificador",
            "axisConstraint": "Restrição de eixo",
            "axisConstraintDesc": "Segure a tecla atribuída ao arrastar para limitar a operação a um eixo.",
            "horizontalOnly": "Somente horizontal",
            "verticalOnly": "Somente vertical",
            "detailSettings": "Configurações Avançadas",
            "longPressDuration": "Duração do toque longo",
            "longPressDesc": "Segure para confirmar quando 'Apenas Modificador' estiver ativado.",
            "preserveWindowOrder": "Manter ordem das janelas",
            "showMenuBarIcon": "Mostrar ícone na barra de menus",
            "launchAtLogin": "Iniciar ao fazer login",
            "restart": "Reiniciar",
            "quit": "Sair",
            "quitAlertTitle": "Sair do Windoor",
            "quitAlertMessage": "Tem certeza que deseja sair?",
            "cancel": "Cancelar",
            "inputKey": "Pressione...",
            "inputLongPress": "Segure...",
            "notSet": "Não definido",
            "sec": "s",
            "leftClick": "Clique Esquerdo",
            "rightClick": "Clique Direito",
            "centerClick": "Clique do Meio",
            "menuSettings": "Configurações...",
            "menuRestart": "Reiniciar Windoor",
            "menuQuit": "Sair do Windoor"
        ],
        .russian: [
            "systemDefault": "Системные настройки",
            "windowTitle": "Настройки Windoor",
            "languageSettings": "Язык",
            "conflictWarning": "Конфликт настроек",
            "moveWindow": "Перемещение",
            "resizeWindow": "Изменение размера",
            "anchorPoint": "Точка привязки",
            "topLeft": "Сверху слева",
            "topRight": "Сверху справа",
            "bottomLeft": "Снизу слева",
            "bottomRight": "Снизу справа",
            "nearestCorner": "Ближний угол",
            "farthestCorner": "Дальний угол",
            "modifierKey": "Модификатор",
            "click": "Клик",
            "leftClickOnlyWarning": "Нельзя настроить только левый клик",
            "modifierOnly": "Только модификатор",
            "axisConstraint": "Ограничение оси",
            "axisConstraintDesc": "Удерживайте назначенную клавишу при перетаскивании, чтобы ограничить действие одной осью.",
            "horizontalOnly": "Только по горизонтали",
            "verticalOnly": "Только по вертикали",
            "detailSettings": "Дополнительно",
            "longPressDuration": "Длительность нажатия",
            "longPressDesc": "Удерживайте клавишу для подтверждения.",
            "preserveWindowOrder": "Сохранять порядок окон",
            "showMenuBarIcon": "Показывать значок в строке меню",
            "launchAtLogin": "Запускать при входе",
            "restart": "Перезапуск",
            "quit": "Выход",
            "quitAlertTitle": "Выйти из Windoor",
            "quitAlertMessage": "Вы уверены, что хотите выйти?",
            "cancel": "Отмена",
            "inputKey": "Нажмите клавишу...",
            "inputLongPress": "Удерживайте...",
            "notSet": "Не задано",
            "sec": "с",
            "leftClick": "Левый клик",
            "rightClick": "Правый клик",
            "centerClick": "Средний клик",
            "menuSettings": "Настройки...",
            "menuRestart": "Перезапустить Windoor",
            "menuQuit": "Выйти из Windoor"
        ]
    ]
    
    func text(_ key: String, language: AppLanguage) -> String {
        let resolvedLang = resolveLanguage(language)
        return translations[resolvedLang]?[key] ?? translations[.english]?[key] ?? key
    }
}
